script:
# select proper step in your build execution and add this line before it
 - sudo netstat -tulpn

language: node_js
node_js:
  - "stable"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: main


 dist: xenial